// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: biblio/biblio.proto

package biblio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mensaje struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Mensaje) Reset() {
	*x = Mensaje{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biblio_biblio_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mensaje) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mensaje) ProtoMessage() {}

func (x *Mensaje) ProtoReflect() protoreflect.Message {
	mi := &file_biblio_biblio_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mensaje.ProtoReflect.Descriptor instead.
func (*Mensaje) Descriptor() ([]byte, []int) {
	return file_biblio_biblio_proto_rawDescGZIP(), []int{0}
}

func (x *Mensaje) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type Chunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tamano int64  `protobuf:"varint,2,opt,name=tamano,proto3" json:"tamano,omitempty"`
	Libro  string `protobuf:"bytes,3,opt,name=libro,proto3" json:"libro,omitempty"`
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biblio_biblio_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_biblio_biblio_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_biblio_biblio_proto_rawDescGZIP(), []int{1}
}

func (x *Chunk) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Chunk) GetTamano() int64 {
	if x != nil {
		return x.Tamano
	}
	return 0
}

func (x *Chunk) GetLibro() string {
	if x != nil {
		return x.Libro
	}
	return ""
}

type UploadLibroRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//	*UploadLibroRequest_Libro
	//	*UploadLibroRequest_Chunk
	Data isUploadLibroRequest_Data `protobuf_oneof:"data"`
}

func (x *UploadLibroRequest) Reset() {
	*x = UploadLibroRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biblio_biblio_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadLibroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLibroRequest) ProtoMessage() {}

func (x *UploadLibroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_biblio_biblio_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLibroRequest.ProtoReflect.Descriptor instead.
func (*UploadLibroRequest) Descriptor() ([]byte, []int) {
	return file_biblio_biblio_proto_rawDescGZIP(), []int{2}
}

func (m *UploadLibroRequest) GetData() isUploadLibroRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *UploadLibroRequest) GetLibro() string {
	if x, ok := x.GetData().(*UploadLibroRequest_Libro); ok {
		return x.Libro
	}
	return ""
}

func (x *UploadLibroRequest) GetChunk() []byte {
	if x, ok := x.GetData().(*UploadLibroRequest_Chunk); ok {
		return x.Chunk
	}
	return nil
}

type isUploadLibroRequest_Data interface {
	isUploadLibroRequest_Data()
}

type UploadLibroRequest_Libro struct {
	Libro string `protobuf:"bytes,1,opt,name=libro,proto3,oneof"`
}

type UploadLibroRequest_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadLibroRequest_Libro) isUploadLibroRequest_Data() {}

func (*UploadLibroRequest_Chunk) isUploadLibroRequest_Data() {}

type UploadLibroResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *UploadLibroResponse) Reset() {
	*x = UploadLibroResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_biblio_biblio_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadLibroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLibroResponse) ProtoMessage() {}

func (x *UploadLibroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_biblio_biblio_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLibroResponse.ProtoReflect.Descriptor instead.
func (*UploadLibroResponse) Descriptor() ([]byte, []int) {
	return file_biblio_biblio_proto_rawDescGZIP(), []int{3}
}

func (x *UploadLibroResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UploadLibroResponse) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_biblio_biblio_proto protoreflect.FileDescriptor

var file_biblio_biblio_proto_rawDesc = []byte{
	0x0a, 0x13, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x2f, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1d, 0x0a, 0x07, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x22, 0x45, 0x0a, 0x05, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x74, 0x61, 0x6d, 0x61, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74,
	0x61, 0x6d, 0x61, 0x6e, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x22, 0x4c, 0x0a, 0x12, 0x55,
	0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x05, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x05, 0x6c, 0x69, 0x62, 0x72, 0x6f, 0x12, 0x16, 0x0a, 0x05, 0x63, 0x68, 0x75,
	0x6e, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x05, 0x63, 0x68, 0x75, 0x6e,
	0x6b, 0x42, 0x06, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x6c,
	0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x32, 0x8b, 0x01, 0x0a, 0x0d, 0x42, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x06, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x12, 0x06, 0x2e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x1a, 0x08, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61,
	0x6a, 0x65, 0x22, 0x00, 0x12, 0x1e, 0x0a, 0x08, 0x55, 0x6e, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x73,
	0x12, 0x08, 0x2e, 0x4d, 0x65, 0x6e, 0x73, 0x61, 0x6a, 0x65, 0x1a, 0x06, 0x2e, 0x43, 0x68, 0x75,
	0x6e, 0x6b, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69,
	0x62, 0x72, 0x6f, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x69, 0x62, 0x72,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x4c, 0x69, 0x62, 0x72, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x28, 0x01, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x69, 0x67, 0x75, 0x74, 0x69, 0x65, 0x72, 0x2f, 0x74, 0x61, 0x72, 0x65, 0x61, 0x32,
	0x73, 0x64, 0x2f, 0x62, 0x69, 0x62, 0x6c, 0x69, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_biblio_biblio_proto_rawDescOnce sync.Once
	file_biblio_biblio_proto_rawDescData = file_biblio_biblio_proto_rawDesc
)

func file_biblio_biblio_proto_rawDescGZIP() []byte {
	file_biblio_biblio_proto_rawDescOnce.Do(func() {
		file_biblio_biblio_proto_rawDescData = protoimpl.X.CompressGZIP(file_biblio_biblio_proto_rawDescData)
	})
	return file_biblio_biblio_proto_rawDescData
}

var file_biblio_biblio_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_biblio_biblio_proto_goTypes = []interface{}{
	(*Mensaje)(nil),             // 0: Mensaje
	(*Chunk)(nil),               // 1: Chunk
	(*UploadLibroRequest)(nil),  // 2: UploadLibroRequest
	(*UploadLibroResponse)(nil), // 3: UploadLibroResponse
}
var file_biblio_biblio_proto_depIdxs = []int32{
	1, // 0: BiblioService.Chunks:input_type -> Chunk
	0, // 1: BiblioService.UnChunks:input_type -> Mensaje
	2, // 2: BiblioService.UploadLibro:input_type -> UploadLibroRequest
	0, // 3: BiblioService.Chunks:output_type -> Mensaje
	1, // 4: BiblioService.UnChunks:output_type -> Chunk
	3, // 5: BiblioService.UploadLibro:output_type -> UploadLibroResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_biblio_biblio_proto_init() }
func file_biblio_biblio_proto_init() {
	if File_biblio_biblio_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_biblio_biblio_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mensaje); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biblio_biblio_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biblio_biblio_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadLibroRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_biblio_biblio_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadLibroResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_biblio_biblio_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*UploadLibroRequest_Libro)(nil),
		(*UploadLibroRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_biblio_biblio_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_biblio_biblio_proto_goTypes,
		DependencyIndexes: file_biblio_biblio_proto_depIdxs,
		MessageInfos:      file_biblio_biblio_proto_msgTypes,
	}.Build()
	File_biblio_biblio_proto = out.File
	file_biblio_biblio_proto_rawDesc = nil
	file_biblio_biblio_proto_goTypes = nil
	file_biblio_biblio_proto_depIdxs = nil
}
